version: '3.7'

services:
    rd-demo:
        image: hoangthanhlam1984/rd-demo:development
        restart: unless-stopped
        ports:
            - 9002:9000
            - 81:80
        user: 1000:1000
        working_dir: /var/www/redis-demo

    rd-demo-queue:
        image: hoangthanhlam1984/rd-demo:development
        restart: unless-stopped
        command: ["php artisan queue:work --tries=1"]
        user: 1000:1000
        working_dir: /var/www/redis-demo
