version: '3.7'

services:
    ws-demo:
        image: hoangthanhlam1984/rd-demo:staging
        restart: unless-stopped
        ports:
            - 9002:9000
            - 81:80
        user: 1000:1000
        working_dir: /var/www/redis-demo
